# err: err2: func `fun2` does not exist in this scope
