# err: errSetScope: func `fun2` does not exist in this scope
